import { useRef, useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { leonApi } from '@/lib/api';
import { colors } from '@/theme';
import type { ChatMessage } from '@/types/api';

const welcome: ChatMessage = { id: 'welcome', role: 'assistant', content: 'I’m here. What would you like to explore, create, or set in motion?', createdAt: 0 };
export function ChatScreen() {
  const [messages, setMessages] = useState<ChatMessage[]>([welcome]); const [draft, setDraft] = useState(''); const [sending, setSending] = useState(false); const input = useRef<TextInput>(null);
  async function send() { const content = draft.trim(); if (!content || sending) return; const user: ChatMessage = { id: `u-${Date.now()}`, role: 'user', content, createdAt: Date.now() }; setMessages((current) => [...current, user]); setDraft(''); setSending(true); try { const result = await leonApi.chat(content); setMessages((current) => [...current, { id: `a-${Date.now()}`, role: 'assistant', content: result.assistant, createdAt: Date.now() }]); } catch (e) { setMessages((current) => [...current, { id: `error-${Date.now()}`, role: 'assistant', content: e instanceof Error ? e.message : 'The signal was interrupted.', createdAt: Date.now() }]); } finally { setSending(false); input.current?.focus(); } }
  return <Screen scroll={false}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.wrap}><View><Text style={styles.eyebrow}>DIRECT SIGNAL</Text><Text style={styles.title}>Converse with LEON</Text></View><View style={styles.thread}>{messages.map((message) => <View key={message.id} style={[styles.message, message.role === 'user' ? styles.user : styles.assistant]}><Text style={styles.messageText}>{message.content}</Text></View>)}{sending ? <Text style={styles.thinking}>LEON is considering…</Text> : null}</View><View style={styles.composer}><TextInput ref={input} accessibilityLabel="Message LEON" value={draft} onChangeText={setDraft} onSubmitEditing={() => { void send(); }} placeholder="Speak your intent…" placeholderTextColor={colors.muted} style={styles.input} multiline /><Pressable accessibilityRole="button" accessibilityLabel="Send message" onPress={() => { void send(); }} style={[styles.send, (!draft.trim() || sending) && styles.disabled]}><Text style={styles.sendText}>↑</Text></Pressable></View></KeyboardAvoidingView></Screen>;
}
const styles = StyleSheet.create({ wrap: { flex: 1 }, eyebrow: { color: colors.gold, fontSize: 10, letterSpacing: 2, marginTop: 8 }, title: { color: colors.text, fontSize: 28, fontWeight: '300', marginTop: 9 }, thread: { flex: 1, justifyContent: 'flex-end', paddingVertical: 20, gap: 10 }, message: { maxWidth: '86%', padding: 14, borderRadius: 17 }, assistant: { alignSelf: 'flex-start', backgroundColor: colors.glass, borderWidth: 1, borderColor: colors.line }, user: { alignSelf: 'flex-end', backgroundColor: '#34325B' }, messageText: { color: colors.text, lineHeight: 21, fontSize: 14 }, thinking: { color: colors.muted, fontStyle: 'italic', fontSize: 12, marginTop: 5 }, composer: { minHeight: 59, borderRadius: 18, backgroundColor: colors.surfaceRaised, borderWidth: 1, borderColor: colors.line, padding: 7, flexDirection: 'row', alignItems: 'center' }, input: { color: colors.text, fontSize: 15, flex: 1, maxHeight: 100, paddingHorizontal: 10, paddingVertical: 8 }, send: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.gold }, disabled: { opacity: .45 }, sendText: { color: colors.ink, fontSize: 22, fontWeight: '500' } });
