import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { leonApi } from '@/lib/api';
import { colors } from '@/theme';
import type { LeonTask, TaskLog } from '@/types/api';

export function TaskDetailScreen({ task: initial, onBack }: { task: LeonTask; onBack: () => void }) {
  const [task, setTask] = useState(initial); const [logs, setLogs] = useState<TaskLog[]>([]); const [loading, setLoading] = useState(true);
  const refresh = useCallback(async () => { try { const [latest, events] = await Promise.all([leonApi.task(initial.id), leonApi.taskLogs(initial.id)]); setTask(latest); setLogs(events); } finally { setLoading(false); } }, [initial.id]);
  useEffect(() => { void refresh(); }, [refresh]);
  const canCancel = task.status === 'queued' || task.status === 'running';
  return <Screen><Pressable onPress={onBack} style={styles.back}><Text style={styles.backText}>← Missions</Text></Pressable><Text style={styles.eyebrow}>MISSION {task.id}</Text><Text style={styles.title}>{task.title}</Text><View style={styles.card}><Text style={styles.label}>CURRENT STAGE</Text><Text style={styles.stage}>{task.current_stage || 'Awaiting trajectory'}</Text><Text style={styles.progress}>{task.progress}% complete · {task.status}</Text></View><Text style={styles.label}>TRANSMISSION LOG</Text>{loading ? <ActivityIndicator color={colors.violet} style={{ marginTop: 20 }} /> : logs.length ? logs.map((log, index) => <View key={`${log.timestamp}-${index}`} style={styles.log}><View style={styles.dot} /><View><Text style={styles.logStage}>{log.stage}</Text><Text style={styles.logMessage}>{log.message}</Text></View></View>) : <Text style={styles.none}>No telemetry has arrived yet.</Text>}<View style={styles.buttons}><Pressable onPress={() => { setLoading(true); void refresh(); }} style={styles.secondary}><Text style={styles.secondaryText}>Refresh</Text></Pressable>{canCancel ? <Pressable onPress={() => { void leonApi.cancelTask(task.id).then(setTask); }} style={styles.cancel}><Text style={styles.cancelText}>Abort mission</Text></Pressable> : null}</View></Screen>;
}
const styles = StyleSheet.create({ back: { paddingVertical: 10, alignSelf: 'flex-start' }, backText: { color: colors.blue, fontSize: 14 }, eyebrow: { color: colors.gold, letterSpacing: 2, fontSize: 10, marginTop: 18 }, title: { color: colors.text, fontSize: 29, fontWeight: '300', marginTop: 9, marginBottom: 21 }, card: { borderRadius: 18, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.glass, padding: 18, marginBottom: 25 }, label: { color: colors.muted, letterSpacing: 1.5, fontSize: 10 }, stage: { color: colors.text, fontSize: 17, marginTop: 9 }, progress: { color: colors.violet, fontSize: 12, marginTop: 15 }, log: { flexDirection: 'row', gap: 12, paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: colors.line }, dot: { height: 7, width: 7, borderRadius: 8, backgroundColor: colors.gold, marginTop: 5 }, logStage: { color: colors.text, fontSize: 13, fontWeight: '600', textTransform: 'capitalize' }, logMessage: { color: colors.muted, marginTop: 4, lineHeight: 18, fontSize: 13, flexShrink: 1 }, none: { color: colors.muted, marginTop: 15 }, buttons: { flexDirection: 'row', gap: 10, marginTop: 23 }, secondary: { padding: 13, borderRadius: 13, borderWidth: 1, borderColor: colors.line }, secondaryText: { color: colors.text }, cancel: { padding: 13, borderRadius: 13, backgroundColor: 'rgba(228,155,153,.12)' }, cancelText: { color: colors.danger } });
